# config/initializers/operation_library.rb
require Rails.root.join('app', 'operation_library', 'operation')
require Rails.root.join('app', 'operation_library', 'operations', 'standard_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'hard_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'chromic_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'chemical_conversions')
require Rails.root.join('app', 'operation_library', 'operations', 'rinse_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'electroless_nickel_plate')
require Rails.root.join('app', 'operation_library', 'operations', 'degrease_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'contract_review_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'pack_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'inspect_final_inspect_vat_inspect')
require Rails.root.join('app', 'operation_library', 'operations', 'jig_unjig')
require Rails.root.join('app', 'operation_library', 'operations', 'enp_strip_mask')
require Rails.root.join('app', 'operation_library', 'operations', 'masking')
require Rails.root.join('app', 'operation_library', 'operations', 'stripping')
require Rails.root.join('app', 'operation_library', 'operations', 'pretreatments')
require Rails.root.join('app', 'operation_library', 'operations', 'sealing')
require Rails.root.join('app', 'operation_library', 'operations', 'water_break_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'dye')
require Rails.root.join('app', 'operation_library', 'operations', 'ptfe')
