# config/initializers/operation_library.rb
require Rails.root.join('app', 'operation_library', 'operation')
require Rails.root.join('app', 'operation_library', 'operations', 'standard_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'hard_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'chromic_anodising')
require Rails.root.join('app', 'operation_library', 'operations', 'chemical_conversions')
require Rails.root.join('app', 'operation_library', 'operations', 'rinse_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'electroless_nickel_plate')
require Rails.root.join('app', 'operation_library', 'operations', 'degrease_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'contract_review_operations')
require Rails.root.join('app', 'operation_library', 'operations', 'pack_operations')
